default: &default
  host: localhost
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
