#!/usr/bin/env ruby

require 'english'
require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changed_files = `git status --porcelain`.split(/\n/).
    select { |file_name_with_status|
      file_name_with_status =~ ADDED_OR_MODIFIED
    }.
    map { |file_name_with_status|
      file_name_with_status.split(' ')[1]
    }.
    select { |file_name|
      File.extname(file_name) == '.rb'
    }.join(' ')

unless changed_files.empty?
  puts "Running RuboCop cops..."
  result = system("rubocop --require rubocop-rails #{changed_files} --auto-correct")
  if result
    puts "+--------------------------------+"
    puts "|                                |"
    puts "|           All good!            |"
    puts "|                                |"
    puts "+--------------------------------+"
  else
    puts "+-----------------------------------+"
    puts "|                                   |"
    puts "|  Fix the RuboCop offences first!  |"
    puts "|                                   |"
    puts "+-----------------------------------+"
    exit 1
  end
end
